### ISSUE TITLE
IP Whois improvement

### ISSUE THREAD

**Issue by zymase** [andy-portmen/country-flags#1]
Hi,

 _Country Flags & IP Whois 0.1.2_ on Firefox 51.0.1 (x64)

There are many Whois sites on the market. The one chosen for _Country Flags & IP Whois 0.1.2_ is 
`isc.sans.edu`
I propose to change it (as I did) to 
`tcpiputils.com`

For two reasons,
1- If _isc.sans.edu_ is accessed with a reasonable delay, on another hand it's quest of IP Whois resolution is excessively slow;
2- IMO _tcpiputils.com_ is far more complete than _isc.sans.edu_

To achieve this here I took the liberty of modifying for myself only of course:

```
[User profile]\extensions\{802a552e-13d1-4683-a40a-1e5325fba4bb}\common.js
Line 140 : 
Replace 
https://isc.sans.edu/ipinfo.html?ip=
with
http://www.tcpiputils.com/browse/ip-address/
```
Works fine, excellent Whois and fast access

**Comment by sirx** [comment]
I agree with this, the ip look up from isc.sand.edu is kinda broken it doesn't show any information.

**Comment by andy-portmen** [comment]
Thanks. Will have this new one on the next release
