### ISSUE TITLE
Excessive Permissions requested since 0.1.5

### ISSUE THREAD

**Issue by Termuellinator** [andy-portmen/country-flags#10]
i'm shocked at what permissions are requested for 0.1.5 - is there any reason to do so?
still sticking with 0.1.4 for now - this extend of permissions is to much for a flag-tool imho (unless there are reasons i can't think of? )

**Comment by andy-portmen** [comment]
0.2.0 has many new features. 

For permissions check https://add0n.com/country-flags.html#permissions

**Comment by andy-portmen** [comment]
New permissions are `nativeMessaging`, `downloads`, and `clipboardWrite`. 

If I wanted to only submit this to Chrome Webstore, I would have inserted all the new permissions in the optional section. Though Firefox only accepts a few permissions as optional ones.

**Comment by Termuellinator** [comment]
ah ok, they looked much worse in the install-dialoge. may i ask what downloads and nativeMessaging are needed for?

**Comment by andy-portmen** [comment]
Both permissions are part of SOCKS bypassing as explained in https://add0n.com/country-flags.html#faq7

**Comment by Termuellinator** [comment]
oh, ok - that makes sense then ^^
thanks for the explanation - and for the great addon! the new features are quite neat :)
