### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by x10GitHub** [andy-portmen/country-flags#11]
Very useful add-on!
Have you thought of localising it?

**Comment by andy-portmen** [comment]
Most parts are now localizable! Please create a new locale JSON file and request a pull merge to see how it works. We can fix whatever is left then!
https://github.com/andy-portmen/country-flags/tree/master/_locales/en

**Comment by x10GitHub** [comment]
The next challenge in localisation would be the translation of the country names. This could be important because many country names are completely different from those in English.
I could help you with creating the localization structure (.json file) as you define it.

All the best!

**Comment by andy-portmen** [comment]
I added all the iso codes to the translation file. This way they can be translated with locales.

**Comment by x10GitHub** [comment]
There are two strings left unlocalisable:
  _"description"_, in manifest.json
  _"Save"_ button label, in index.html

**Comment by andy-portmen** [comment]
> There are two strings left unlocalisable

Fixed! Thanks.
