### ISSUE TITLE
cache4.buffer is not ready when FF starts

### ISSUE THREAD

**Issue by Acid-Crash** [andy-portmen/country-flags#14]
After PC reboot and FF launch there is ar error icon with the following message.
error cache4.buffer is not ready
https://i.paste.pics/72be93050c02d806c265bf924cff836e.png
Happened on FF56 and latest Nightly. Running Win10 x64
Lastly happened with https://www.reddit.com/r/FirefoxCSS/new/

**Comment by andy-portmen** [comment]
So how can I reproduce this? Do you have your FF set to restore tabs after a reboot? Any other settings?

**Comment by Acid-Crash** [comment]
Usually this happens when FF launches with some tabs from the last session. 
Unfortunately this happens randomly without no specific pattern.
My settings are as follows:
On start - Show your windows and tabs from last time. 
Allow all cookies. 
Clear history when FF/Nightly closes -  cache, cookies.

**Comment by andy-portmen** [comment]
This should have been fixed. Please wait for the next release and reopen if not. Thanks for the report.
