### ISSUE TITLE
Extension doesn't always initialize on browser launch homepage

### ISSUE THREAD

**Issue by narcolepticinsomniac** [andy-portmen/country-flags#24]
Similar to: 
https://github.com/Tampermonkey/tampermonkey/issues/345 
so perhaps useful.

**Comment by andy-portmen** [comment]
do you get the error flag?

**Comment by narcolepticinsomniac** [comment]
IDK what the error flag is, but it's the same grayscale "9" icon that shows on chrome:// URLs. Just like with TM, or Stylish long before that, it doesn't fail every time, it's more a crap-shoot. I have Google as my homepage, and sometimes when I launch the browser, there's an American flag, sometimes the script fails to load and there's the grayscale "9". Not the end of the world, but I consider the script sometimes failing on browser launch a bug. Other than that, handy extension BTW.

**Comment by andy-portmen** [comment]
Okay got it. Seems like the background script is loading with delay. I added a new module to scan the existing tabs and update the icon when the extension is fully loaded.

Thanks for the report!

**Comment by narcolepticinsomniac** [comment]
Nice. Hadn't given it much thought, but I started wondering why the "9". Oh, probably because it isn't one. It's one of those map icons, but with a weird curve at the bottom. I've only ever seen them symmetrical, like:

![image](https://user-images.githubusercontent.com/14100003/31709539-51e3c2a0-b3c0-11e7-8385-df3bc138ede3.png)
 
Either way, mystery solved and bug fixed, thanks.
