### ISSUE TITLE
Adding more services

### ISSUE THREAD

**Issue by nonoscope** [andy-portmen/country-flags#26]
Thank you for this add-on, which is the only WebExtensions API compatible replacement of Flagfox.
It is almost as close as can be feature-wise, considering the WebExtensions API to be the main limiting factor.

As we are limited only to 6 displayable services, could you make the predefined service names (ping, whois, etc) editable in addition to service URLs or add more empty slots? I find the 2 empty slots for user defined services to be insufficient. I have no use for most of the predefined services and would like to add my own (eg google cache, archive.is, builtwith, w3c, reputation and security checks, etc). Would it be possible?

**Comment by andy-portmen** [comment]
So we have many new services. I hope the default ones are enough for you. If not you can add up to 5 custom commands to the right-click menu.

Please check the latest dev version and let me know if there is a service that might be useful to other users and it is still missing in the options page;
https://github.com/andy-portmen/country-flags/archive/master.zip
Download the XPI and extract it into a directory
Now open about:debugging in a browser tab and use the "Load Temporary add-on" to load the extension by pointing it into `WebExtension/manifest.json`.

**Comment by nonoscope** [comment]
Looks like most of the popular services is included now and there's more room to add my own so the issue can be considered as solved. Thank you.
