### ISSUE TITLE
Support for goo.gl

### ISSUE THREAD

**Issue by gbcox** [andy-portmen/country-flags#29]
Is it possible to support goo.gl.  Looks like it requires oauth to access the requester google account:
https://developers.google.com/url-shortener/v1/getting_started

I know there are separate extensions that can do this, but would be nice if it could also be rolled into this one.  Just a suggestion.

**Comment by Taurean75** [comment]
You'd need to use a Google API.

https://addons.mozilla.org/en-US/firefox/addon/shorten_me/

**Comment by andy-portmen** [comment]
If anybody is interested in writing a module for it we can add

**Comment by gbcox** [comment]
Google is terminating support for goo.gl - https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html; so this request is no longer valid.  Closing.
