### ISSUE TITLE
Optional Features Not Appearing 

### ISSUE THREAD

**Issue by Taurean75** [andy-portmen/country-flags#30]
Only default ones appear...
![default](https://user-images.githubusercontent.com/8365855/32702763-5e209f40-c7a0-11e7-9eb6-4081ced83e8d.png)

![options](https://user-images.githubusercontent.com/8365855/32702792-bba3db32-c7a0-11e7-82e7-a09a66ee5b70.PNG)

I'm using Firefox 57 x64.

**Comment by Taurean75** [comment]
Only 6 options appear.  Is this intentional?

**Comment by andy-portmen** [comment]
No this is a WebExtension limitation. There is no workaround for it.

**Comment by d4k0** [comment]
Hi,
[this add-on](https://addons.mozilla.org/de/firefox/addon/undoclosetabbutton/) uses a submenu to circumvent this restriction. Here is its github repository:

https://github.com/M-Reimer/undoclosetab

I'm not sure if this is only possible with buttons, though. But maybe you can have a look at it :).

**Comment by andy-portmen** [comment]
@d4k0 nice!

We have it on the dev version
![screen shot 2017-11-17 at 11 44 11 am](https://user-images.githubusercontent.com/6779535/32937292-1e5ea41a-cb8d-11e7-89ed-e8e5d44efde5.png)

@x10GitHub,  @Termuellinator and @Djfe guys would you please update the locales

**Comment by d4k0** [comment]
Very cool, thanks!

**Comment by Taurean75** [comment]
Cool!

**Comment by x10GitHub** [comment]
It's quite cool!
The webstore description should be updated too.

**Comment by andy-portmen** [comment]
@x10GitHub Thanks. The webstore description is updated.

**Comment by Djfe** [comment]
sry for hijacking, but I need some info for translating the commit from above:
What do you mean by "Optimizing code to access minimum number of possible requests"
Have you reduced the number of requests happening in the background?
What do you mean by "accessing requests"?

**Comment by andy-portmen** [comment]
I am just too lazy to write proper changelogs! Go with these replacements. I'll update the "En" locale.

> Optimizing code to access minimum number of possible requests

Reduces the total number of background requests for resolving country codes from IP addresses.

> Checking local IP before searching databases

Do not call the country code resolution worker if an IP address in the local range.

> Extension now refreshes all the badges upon start-up

Extension now requests country code resolution for all open tabs upon start-up

> the DB is local, right?

Yes!

**Comment by Djfe** [comment]
I don't need proper changelogs ^^ (these are fine)
But certain aspects weren't clear to me, which would've lead to a rough translation, if I hadn't asked.
So thx for clearing that up :)

I'll send you a pull request ;)

**Comment by d4k0** [comment]
I just received the update and this new feature is working just fine. The "problem" now is that _**ALL**_ services are listed in the "Other services" menu and not just those that I selected in the settings. Is there a technical reason for that or is it just a bug?

**Comment by Djfe** [comment]
according to the changelog:
intentional

Maybe the settings should indicate it somehow when more than 5 checkboxes are ticked.
Or everything checked above 5 could at the top of the others menu.

**Comment by andy-portmen** [comment]
> everything checked above 5 could at the top of the others menu.

This sound like a good idea. We will have this on the next release.
