### ISSUE TITLE
non translatable strings

### ISSUE THREAD

**Issue by Djfe** [andy-portmen/country-flags#32]
I found two strings that aren't translatable at the moment:
"Don't Show in Address Bar"
"Manage Extension..."
"Country Flags & IP Whois" (hovertitle of the icon)

**Comment by andy-portmen** [comment]
> "Don't Show in Address Bar"
> "Manage Extension..."

Chrome injects these context-menu items and they have your browser locale.

**Comment by andy-portmen** [comment]
> "Country Flags & IP Whois" (hovertitle of the icon)

This is the actual name of this extension. Although it is possible to make it localize-able, I think this is not a good idea. It would be hard to find the extension later if the localized name is used.

**Comment by Djfe** [comment]
ok
I'm using Firefox 59 btw.
And Firefox uses the english locale instead of german for the first and second string, I mentioned.
Might be a bug in Firefox, should I report it on bugzilla?

**Comment by andy-portmen** [comment]
> I'm using Firefox 59 btw.
Nice!

I would say they will fix this soon!
