### ISSUE TITLE
Add PTR to title

### ISSUE THREAD

**Issue by darnux** [andy-portmen/country-flags#39]
Hi, I just discovered your addon and I really like it.
One thing I would suggest is to add the PTR of the IP on the title tab (when you hovering the flag icon).

Do you execpt BTC/ETH/LTC/... as donation also?

**Comment by andy-portmen** [comment]
do you mean the PTR Record? How can we get that?

> Do you execpt BTC/ETH/LTC/... as donation also?

There is a link for BTC in the FAQs page if you prefer that.

**Comment by darnux** [comment]
> do you mean the PTR Record? How can we get that?

Yes correct. On a terminal you could run `host [IP_ADDRESS]` our the information can be extracted from tcpiputils.com also.
Maybe this module can do the trick?

https://www.npmjs.com/package/ip-ptr

**Comment by andy-portmen** [comment]
Okay so as of the next release, you can run any custom OS level command after a flag for a tab is resolved. For your case you can run `host [ip]`. The output of this command will be appended to the tooltip.

![screen shot 2017-11-28 at 4 45 29 pm](https://user-images.githubusercontent.com/6779535/33321664-b5599402-d45b-11e7-99d3-ab0f17c91578.png)
