### ISSUE TITLE
does not work on Firefox when RequestPolicy is also enabled

### ISSUE THREAD

**Issue by dkg** [andy-portmen/country-flags#4]
When the RequestPolicy (https://requestpolicycontinued.github.io/) is co-installed on the same firefox profile, the country-flags extension doesn't show any flags.

Disabling RequestPolicy and restarting the browser lets country-flags work again.  I'm not sure the right way to resolve this, but just wanted to give a heads-up, since these are both useful extensions.

**Comment by andy-portmen** [comment]
I just tested this and it works fine for me. Any particular changes on the default settings of RequestPolicy add-on?

Since this add-on uses local database, I dont see how RequestPolicy add-on causes conflicts with it.
