### ISSUE TITLE
No flag displayed after back/forward navigation

### ISSUE THREAD

**Issue by ygoe** [andy-portmen/country-flags#40]
The flag in the address bar in Firefox is not displayed if the page wasn't freshly loaded but revisited with back/forward history navigation.

Version 0.2.3 in Firefox 57.0

**Comment by ygoe** [comment]
The flag is also missing in a restored tab after restarting Firefox, with session restore enabled.

**Comment by andy-portmen** [comment]
Both will be fixed by the next release. Thanks for the report.
