### ISSUE TITLE
 Recongnize True IP Of the Server

### ISSUE THREAD

**Issue by BurgerTown** [andy-portmen/country-flags#48]
U done a good job I like this addon 
But I have to use proxy server to  connect some specified website like google
In that case,IP will be a internal IP address like '127.0.0.1' which this addon cannot be get the right ip either flag of that server
So if it is possible that this addon could recognize that i am using a proxy server to access this website
And got the true server IP though proxy so display the right flag and ip

**Comment by andy-portmen** [comment]
FAQ 7?
https://add0n.com/country-flags.html

**Comment by BurgerTown** [comment]
It is a good solution which use a proxy on system level
But i use SwitchyOmega on Chrome which i can control which website to proxy
So there is a little problem 
[![LHDfg.png](https://s1.ax1x.com/2017/12/17/LHDfg.png)](https://imgchr.com/i/LHBtS)

**Comment by BurgerTown** [comment]
THX
