### ISSUE TITLE
Extensions is not able tot get 'real' ip address if connect through proxy

### ISSUE THREAD

**Issue by heubergen** [andy-portmen/country-flags#5]
I'm connected behind a proxy in my company. The extensions seems not be able to get the 'real' ip address from the server.

For example the GOV site from Switzerland (https://www.admin.ch) which is clearly hosted in switzerland.
STR:
1. Install Country Flags
2. Configure a proxy
3. Open https://www.admin.ch

**Comment by c33s** [comment]
same problem here. 
https://addons.mozilla.org/en-US/firefox/addon/server-ip has the same problem

**Comment by andy-portmen** [comment]
When a proxy server is set, this server is the first external server and hence there is no way for the browser to detect the actual server's IP address. 

In the new version, you can ask the extension to use your OS level DNS resolver. If this option is enabled, the extension will display the correct IP address and hence the correct flag.
