### ISSUE TITLE
Flags not showing

### ISSUE THREAD

**Issue by rbartlejr** [andy-portmen/country-flags#50]
v0.2.4 and not showing flags. Shows error triangle. Have tried refreshing but does not help.

**Comment by andy-portmen** [comment]
Place your mouse other the button. Do you see any error log?

**Comment by Taurean75** [comment]
@andy-portmen, I get "outside IPv4 range" on most sites in Firefox 58.

**Comment by MarkSpizu** [comment]
I get the same triangle (error Undefined) with 0.2.6. Andy, an you fix it? :)

Back to 0.2.5 and the EU flag is showing.

This is the website https://www.nwradu.ro

**Comment by MarkSpizu** [comment]
Yes, just tested 0.2.7 and it's fixed. Thanks a lot Andy!

**Comment by MarkSpizu** [comment]
With 0.2.8 the issue is back. This time is just blank Country Flags logo.

**Comment by andy-portmen** [comment]
this time this is not a bug, but the IP is not listed in the database; you can test it here https://www.maxmind.com/en/geoip-demo

**Comment by MarkSpizu** [comment]
Back to 0.2.7 and I see 176.223.226.110 Europe.

**Comment by MarkSpizu** [comment]
With 0.2.8 there's no IP even on ebay.com

**Comment by andy-portmen** [comment]
Should have been fixed in the new release. Let me know if not.

**Comment by MarkSpizu** [comment]
All fixed with 0.2.9. Thanks again Andy!
