### ISSUE TITLE
doesn't work with vpn addons

### ISSUE THREAD

**Issue by choomchichi** [andy-portmen/country-flags#53]
when a vpn addon is installed, this always shows the vpn ip, not the server ip.
but this one correctly works, maybe it can help:
https://addons.mozilla.org/en-US/firefox/addon/full-ip-info/
thanks

**Comment by andy-portmen** [comment]
FAQ7?
https://add0n.com/country-flags.html

**Comment by choomchichi** [comment]
thank you for your replying,
I tried this, but doesn't work. The "open in ..." addons work perfectly, but this one doesn't work.
I enabled the "native dns resolver" option, and the external command too. the external command works but the flag is still the same as my vpn country every where.

**Comment by andy-portmen** [comment]
So the extension uses your OS to resolve the DNS. This simple NodeJS code is used

```js
require('dns').lookup('www.google.com', (err, address, family) => console.log(err, address, family))
```

Please try it on NodeJS and see if you can play with the code to fix the issue. If so we can push an update!

**Comment by choomchichi** [comment]
Thank you so much,
I'll try soon.
