### ISSUE TITLE
"Server is on your private network"

### ISSUE THREAD

**Issue by Rigido71** [andy-portmen/country-flags#58]
Hi,
I use "Proxy Switcher" to choose between "Direct" and "Manual" settings.
When a proxy server is set, every page says the server is on private network, shows a "192" icon and reports proxy IP address.
I think the problem is not the proxy itself as company set an "always through proxy" rule and, if I set "Direct"connection, flags and IP addresses are shown right.

Thanks.

**Comment by andy-portmen** [comment]
FAQ7? https://add0n.com/country-flags.html

**Comment by Rigido71** [comment]
Sorry, I didn't see that, the problem is that I don't know if it is a SOCKS server, 
I set addresses for HTTP, SSL and FTP proxy and HTTP server type.

**Comment by andy-portmen** [comment]
It is defiantly a socks server since it is routing your DNS traffic and hence the browser reporting a local server as the actual server. You need to follow the FAQ to allow the extension to use the native method to convert hostnames to IP addresses.

**Comment by Rigido71** [comment]
Thank you.

**Comment by yoyo837** [comment]
> FAQ7? https://add0n.com/country-flags.html

Where to download the `native DNS resolver`?
