### ISSUE TITLE
[REQ] Add context menu with some option, like copy IP

### ISSUE THREAD

**Issue by dehghani-mehdi** [andy-portmen/country-flags#6]
Hey,

Thanks for your great add-on. could you please add ability to right-click on the flag and can copy the IP?

**Comment by TheFinalCut83** [comment]
@andy-portmen, please add some options to right-click menu like in Flagfox: SSL server test, tinyurl, ping and trace tools. Ability to add and customize these options would be nice too.

**Comment by andy-portmen** [comment]
I added the following right-click context menu items:

SSL Checker
Trace Route
Ping
DNS Lookup
Whois Lookup
HTTP Headers

Note that the URL for each service can be edited from the options page.

Since we are limited to 6 items, do we prefer to replace one of these services with copy IP?

**Comment by andy-portmen** [comment]
Also note that currently only Chrome version supports these right-click menu items. Please give the new version a try and if it works as expected I'll release for Firefox and Opera.

**Comment by TheFinalCut83** [comment]
Working as expected, many thanks! But 2 questions remain: 1) why is this a hard limit of 6 points? 2) is it possible to add a reset of the settings? For example, after changing the URL to their own, after some time it will want to return to the default items.
About Copy IP - personally for me it is not critical; it would be nice to see a tinyurl instead of the HTTP headers or, at least, to fully customize these 6 points (to change not only the URL, but their names)

**Comment by dehghani-mehdi** [comment]
> Since we are limited to 6 items, do we prefer to replace one of these services with copy IP?

Thanks for the support.
Actually I used your add-on because I need the IP of sites that I'm working on, so it would be great to see this option to context menu.

**Comment by andy-portmen** [comment]
We now have 8 tools in the right-click menu. You can select among them from the options page.

**Comment by eadmaster** [comment]
i do not see the context menu entry in the latest chrome version, is this broken now?

**Comment by andy-portmen** [comment]
@eadmaster open "chrome://extensions/" in a browser tab. turn the developer mode on. Open "Inspect Service Worker" of this extension and on the console tab try:

```js
chrome.runtime.reload();
```

**Comment by eadmaster** [comment]
> @eadmaster open "chrome://extensions/" in a browser tab. turn the developer mode on. Open "Inspect Service Worker" of this extension and on the console tab try:
> 
> ```js
> chrome.runtime.reload();
> ```

just tried that, but no error is printed on the console.
btw now i've noticed when i click on the extension icon in the top-right, this error popup "Cannot read properties of undefined (reading 'ip')"

**Comment by andy-portmen** [comment]
Can you also try reinstalling the extension from Chrome Webstore?
