### ISSUE TITLE
Moving Country Flag To Rxtension Bar In Vivaldi

### ISSUE THREAD

**Issue by 2635599** [andy-portmen/country-flags#60]
just reinstalled the vivaldi browser and all looks good. the only issue i've run across is country flag. the extension installa just fine, but it sites in the search box and after appearing for a quick second or two when i go to a site it disappears. in firefox i can move it to the extension bar is there anyway to do that in vivaldi?

**Comment by andy-portmen** [comment]
It seems like an internal browser issue. I am not able to reproduce this on Vivaldi v2.3.1440.60. Do you still have this issue?

**Comment by 2635599** [comment]
no i just forget to closed this. issue resolve ed itself. thanks
