### ISSUE TITLE
Server IP Takes Whole Window

### ISSUE THREAD

**Issue by poita66** [andy-portmen/country-flags#64]
When visiting https://www.razer.com the Server IP iframe takes up the whole window and the close button is off-screen, making it impossible to browse the site without disabling the extension.

**Comment by andy-portmen** [comment]
should have been fixed by 0.1.2 release. Thanks for the report.

**Comment by drowse7en** [comment]
As a convention, hexadecimal in IPv6 is presented in lowercase.  Is it possible to add an option to present hexadecimal in uppercase?
