### ISSUE TITLE
Doesn't work on https://www.virustotal.com

### ISSUE THREAD

**Issue by SeriousHoax** [andy-portmen/country-flags#66]
It doesn't work on https://www.virustotal.com
Why is that?

**Comment by Nikronic** [comment]
@SeriousHoax 
![image](https://user-images.githubusercontent.com/32401852/69987494-db5d9180-1554-11ea-8057-9c17f41ef82c.png)
It works fine for me.

Browser: Edge Chromium 80
OS: Windows 10 Pro

**Comment by SeriousHoax** [comment]
> 
> 
> @SeriousHoax
> ![image](https://user-images.githubusercontent.com/32401852/69987494-db5d9180-1554-11ea-8057-9c17f41ef82c.png)
> It works fine for me.
> 
> Browser: Edge Chromium 80
> OS: Windows 10 Pro

It didn't use to work when I created the issue. Now working on mine too. Closing the issue.
