### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Bamajon1974** [andy-portmen/country-flags#68]
Questions/Feature requests

I am wondering if there are options in Country Flags & IP Whois to hide the "other services" menu when you right click the extension icon in Chrome toolbar (since I would rarely ever access most of those websites anyway) 

and if there is a way to set the left click of extension icon in the Chrome toolbar to go to settings or display the country/host/server/access info (same as when you hover over the icon) rather than go to an IP Whois page.

**Comment by andy-portmen** [comment]
We are going to have two new options. One for removing the other services menu and the other one to adjust the left-click action.

**Comment by Bamajon1974** [comment]
Great! Thank you! When do you anticipate deploying these new features?

**Comment by andy-portmen** [comment]
Version 0.3.6 is submitted to the stores. It usually takes up to 3 days to get reviewed.
