### ISSUE TITLE
v0.1.7 Not Working 

### ISSUE THREAD

**Issue by Taurean75** [andy-portmen/country-flags#7]
Hello --

The flag doesn't appear at all in FF v56. Even in v55, it appeared randomly.

Thanks.

**Comment by andy-portmen** [comment]
It appears if you refresh the tab (to get the IP address of the top request). I just checked the extension on FF 56 and it works as expected. If it is not working for you even after refresh, please open the browser console (Ctrl + Shift + J) and see if you get a relevant error on page refresh.

**Comment by Taurean75** [comment]
Refresh doesn't make it work.

In the console, I get...
`Error: Could not establish connection. Receiving end does not exist.  undefined
Unchecked lastError value: Error: NoMessageListenersError is not defined  ExtensionCommon.jsm:304
Error: WebExtension context not found! ExtensionParent.jsm:778:13
Unchecked lastError value: Error: NoMessageListenersError is not defined`

Hope this helps.

**Comment by andy-portmen** [comment]
Can you try the extension on a clean profile? 

> Error: Could not establish connection. Receiving end does not exist. undefined Unchecked lastError 

This might be relevant but there is no info. There might be a legacy add-on that conflicts.

**Comment by Taurean75** [comment]
It indeed was a conflict with another IP-related WebExtension. Thanks
