### ISSUE TITLE
Flag icon missing sometimes

### ISSUE THREAD

**Issue by Koenvh1** [andy-portmen/country-flags#71]
Recently I have noticed that the flag icon is missing sometimes, both on Chrome 83 and Firefox 79 on Windows 10 64-bit, with the built-in DNS resolver.
![image](https://user-images.githubusercontent.com/5168825/86931849-e571ef00-c138-11ea-82ab-aec7ff5c13fe.png)
(page: https://todoist.com/app, which is a PWA)
If I reload the page using only F5, then the flag does not show up, and it shows the logo. If I refresh the page using Ctrl+F5, it does. It seems like it does not trigger loading the flag icon consistently, or that it cannot handle the page being loaded from cache.

**Comment by andy-portmen** [comment]
Thanks for the report. Should get fixed by the next release. If not please reopen.

**Comment by JayceLau76** [comment]
The issue seems persist after update (0.3.6). It's intermittent, the flag may or may not reappear after F5 on the same page.

**Comment by andy-portmen** [comment]
@JayceLau76 I am not able to reproduce. Is this on FF?
