### ISSUE TITLE
Blurry flags on high dpi/4K screens

### ISSUE THREAD

**Issue by DabuXian** [andy-portmen/country-flags#74]
Not a major issue, but some flags don't look great on Windows with 150% scaling, which is the default on a 4K monitor. Here's a comparison with no scaling.

![flags](https://user-images.githubusercontent.com/4173488/92472803-4b7eff00-f1da-11ea-8d0d-ad342faf2711.png)

**Comment by andy-portmen** [comment]
Based on your report, I added support for 24px icons (1.5 of 16px,  which is the default size). The problem is that at this moment, neither Chrome nor Firefox read the 24x icon, instead they resize the 16px icon that causes the blurry issue. This is the best we can do at the moment.
