### ISSUE TITLE
flags are black and white in firefox nightly

### ISSUE THREAD

**Issue by Speciesx** [andy-portmen/country-flags#76]
Firefox Nightly 

![grafik](https://user-images.githubusercontent.com/1196375/119188181-9bf17080-ba7a-11eb-9e31-4a0b7b703c15.png)

![grafik](https://user-images.githubusercontent.com/1196375/119188251-b297c780-ba7a-11eb-9331-e89973d5a1ab.png)

**Comment by tech189** [comment]
This is now in stable Firefox 89, using the default System theme at night when dark mode is on.
<img width="143" alt="Screenshot 2021-06-01 at 21 45 38" src="https://user-images.githubusercontent.com/10728085/120388349-ed271d00-c322-11eb-9b19-0a91985fdfc7.png">

**Comment by Speciesx** [comment]
Is it possible to move the flag back to the address bar?

**Comment by farag2** [comment]
> Is it possible to move the flag back to the address bar?

The same question.

**Comment by msrn** [comment]
Could you @andy-portmen revert the move from address bar (page action) to toolbar? The flag shown on address bar made much more sense, and it didn't clutter the toolbar.

**Comment by VL4DST3R** [comment]
Came here to complain about the same thing. There's a reason i preferred this addon specifically, which is exactly this: having the flag inside the bar itself. Please revert this change or at least add an option to change it back.

**Comment by andy-portmen** [comment]
Does anybody know an extension with a colorful icon in the address bar (after this major FF update)? I had to move it to the toolbar so that the flags are visible!

**Comment by Termuellinator** [comment]
i don't have the issue with a white flag, but i'd love to move it back into the adress bar, too :)

**Comment by tech189** [comment]
> Does anybody know an extension with a colorful icon in the address bar (after this major FF update)? I had to move it to the toolbar so that the flags are visible!

It looks like @Speciesx has an extension for showing which TLS version a website is using, maybe [this](https://addons.mozilla.org/en-US/firefox/addon/indicatetls/), that seems to keep the colour. Source code looks to be [here](https://github.com/jannispinter/indicatetls)

Just tried it myself, and it appears to be able to display a colourful icon in dark mode.
![image](https://user-images.githubusercontent.com/10728085/120627505-a25cf080-c45b-11eb-8632-208aad8d435a.png)

**Comment by Dominiquini** [comment]
> 
> 
> Does anybody know an extension with a colorful icon in the address bar (after this major FF update)? I had to move it to the toolbar so that the flags are visible!

FoxyTab (https://addons.mozilla.org/en-US/firefox/addon/foxytab/) put a flag in the address bar!

**Comment by VL4DST3R** [comment]
For anyone affected by the issue, until it's fixed, you can revert to and install the previous version of the addon via the ff addon page, and disable automatic updates for now.
