### ISSUE TITLE
Version 0.5.5: Flag moved from address bar to toolbar

### ISSUE THREAD

**Issue by d4k0** [andy-portmen/country-flags#78]
Hi,

after the latest update to version 0.5.5 the flags are now displayed in the toolbar instead of the address bar. Is this a new limitation of Firefox? I'm using Firefox 102.0.1.

**Comment by andy-portmen** [comment]
Thanks for the report. The bug in the "v3tov2" converter script is fixed. The 0.5.5.1 release fixes the issue
