### ISSUE TITLE
Private Windows mode

### ISSUE THREAD

**Issue by aimi617** [andy-portmen/country-flags#79]
The latest version 0.5.5 writes the site cookies in Private Windows mode which is compromising a user privacy. It's not recommended to use this add-on in Private mode. Tested on FF Developer Edition 103.0b9 (64-bit).

**Comment by andy-portmen** [comment]
What do you mean by "writes the site cookies"?

**Comment by aimi617** [comment]
After visiting the site with enabled add-on in private mode we noticed a plenty of saved 3-rd party cookies, somehow the add-on creates a breach in private mode and sites can save the cookies. With disabled add-on the privacy was restored. As a test we switched to private mode, cleared all cookies, enabled add-on, and browsed a set of heavily loaded sites by different trackers, the result is tons of recorded cookies in FF -> Settings -> Privacy & Security -> Manage Data...

**Comment by andy-portmen** [comment]
> browsed a set of heavily loaded sites by different trackers

Can you provide an example website?

**Comment by andy-portmen** [comment]
> somehow the add-on creates a breach in private mode and sites can save the cookies

I just tested the extension on a clean Firefox profile and I am not able to reproduce this. Please provide steps.

**Comment by aimi617** [comment]
The issue still there, please see those 2 sites in a screenshot.

![image](https://user-images.githubusercontent.com/33189191/179339217-e476838d-c2b9-4560-8778-de476f499296.png)

**Comment by andy-portmen** [comment]
I tried these two websites, and although they created cookies in the private mode, there is no entry on "Manage Data..." for me. 

Either another extension is responsible, or you have a corrupted profile. Try on a clean profile with only this extension installed, and let me know if you can still reproduce this. Based on the extension permissions, it is very unlikely it could manipulate cookies.

**Comment by aimi617** [comment]
We also suspect, either a conflict with other extension or corrupted profile. It will take a time to test it, we keep you posted about results.

**Comment by aimi617** [comment]
It's an add-on issue, same cookies appear with all other disabled add-ons, or brand new clear profile, and the same happens in another regular FF 102.0.1 (64-bit). To test it, launch FF, run a private mode, in private FF window go to mk.ru, forward to kp.ru, then back to mk.ru. Keep all browser windows opened, go to Settings, Privacy & Security, open Manage Data, you will see those cookies.

**Comment by andy-portmen** [comment]
Thanks for the report. The extension was using a local fetch to emulate navigation for existing tabs to get the IP address. It turned out that this function was responsible for the cookie creations. It is now fixed on the `0.5.6` release. Please confirm.

**Comment by aimi617** [comment]
No cookies in private mode, thanks for fixing. Is it possible to move Service URLs Up-Down? For example, "Copy IP" is frequently used service and would be nice to move it Up on first position.

**Comment by andy-portmen** [comment]
> Is it possible to move Service URLs Up-Down?

As of the next release, you can sort services from the options page.
