### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by HamidZaeri** [andy-portmen/country-flags#8]
First of all thanks for this great WE addon. 3 suggestion:
- Add custom command like Flagfox (Add, not edit)
- Open tabs in the background.
- Select actions for click, double-click, middle click on the flag.

**Comment by andy-portmen** [comment]
> Select actions for click, double-click, middle click on the flag.

This is not doable in the WebExtension context. There is no middle nor double-click listener.

Other suggestions are implemented in 0.2.0!

**Comment by CodingMarkus** [comment]
This might have been true 2017, but Flagfox is doing exatly that and Flagfox is a WebExtension.
