### ISSUE TITLE
Version 0.5.5.1: Context menu is missing

### ISSUE THREAD

**Issue by d4k0** [andy-portmen/country-flags#80]
Hi,

after you fixed https://github.com/andy-portmen/country-flags/issues/78, the flag is now displayed in the address bar again, but there is no context menu anymore:

![No context menu](https://user-images.githubusercontent.com/10982825/179353520-244934a0-de26-4b2e-bdda-4e556fa180f4.png)

**Comment by andy-portmen** [comment]
Even after a restart?

**Comment by d4k0** [comment]
Thanks, that did the trick!
