### ISSUE TITLE
(request) Indicate when page source is from the cache

### ISSUE THREAD

**Issue by DavidBE-UK** [andy-portmen/country-flags#81]
I'm trying this extension in place of one I used for a long time that showed the country flag but alongside a whole bunch of other tab utilities, none of which I now use all rolled into one. This is good as a country flag only extension, but is missing one feature I liked in that other extension, which showed a symbol instead of the country flag when the page was loaded from the cache rather than being freshly fetched. E.g. after a re-start following a browser update, or a restore previous session after starting the browser again, or Windows performing a restart after a Windows update when the machine is unattended, the browsers restore the pages from the cache rather than fetching them again, and I for one appreciate a reminder that they are cached versions rather than fresh with a 'cached' icon in place of the country flag. Would this be possible (as a configurable option)?

**Comment by andy-portmen** [comment]
Thanks for the suggestion. As of the next release, you will get the "c" badge text if the top frame is loaded from the cache (when the IP address is not resolved by fetching the resource from its server).
