### ISSUE TITLE
Review Vivaldi browser

### ISSUE THREAD

**Issue by ldexterldesign** [andy-portmen/country-flags#84]
https://chrome.google.com/webstore/detail/country-flags-ip-whois/bffjckjhidlcnenenacdahhpbacpgapo

<img width="1840" alt="Screenshot 2022-12-06 at 03 51 29" src="https://user-images.githubusercontent.com/1715809/205808580-bc3c8a90-f797-482c-929b-4a6a5beb591c.png">

😗

**Comment by andy-portmen** [comment]
Try on a clean profile; https://webextension.org/blog/2022/12/06/browser-profiles-are-explained.html

**Comment by ldexterldesign** [comment]
Thanks for quick reply

Not sure what it was but it's working now - nothing changed my side 🤷

Cheers

PS Have deleted https://chrome.google.com/webstore review
