### ISSUE TITLE
xDNS issues, no possibilities to use anymore

### ISSUE THREAD

**Issue by hwprinz** [andy-portmen/country-flags#87]
since the last update, any firefox version only gets 'xDNS:navigation:resolved' or some other xDNS 

only getting the pop-up 'obj is undefined' when directly clicking on it. 
the Copy IP function is only telling: Cannot find the IP address for this tab, Refresh might help

None the less, hovering over the flag still tells a correct resolved IP address but useless, if i cannot use it.
Version 0.6.0 from March 15, 2023

Please.... i NEED it back working

**Comment by andy-portmen** [comment]
Please reopen if you still have the issue with the `0.6.0.1` release.
