### ISSUE TITLE
Waaaaaay too many "red X on white" flags. 

### ISSUE THREAD

**Issue by dallas7** [andy-portmen/country-flags#88]
On hover...
Error: : unidentified  (Yes, two colons.)
Server IP: is correct.
Resolve Method: xDNS:navigation:resolved

That "red X on white flag" flag is on your webextension dot org site, too.

Firefox 110.0.1
Windows 10 Pro 21H2
Thank you.

**Comment by dallas7** [comment]
Forgot to mention:  That "generic" flag is on your webextension dot org site, too.

**Comment by andy-portmen** [comment]
Please reopen if you still have the issue with the `0.6.0.1` release.

**Comment by dallas7** [comment]
Using 0.6.0.1
That "red X on white flag" flag remains on your webextension dot org site.

Sample sites:
UPI dot com
garmin dot com
mailstore dot com
sammyfans dot com

Advise if you need more info about my setup.  If the issue is on my end, I can live with it.  Cheers.
