### ISSUE TITLE
"obj is undefined" error message

### ISSUE THREAD

**Issue by circcc** [andy-portmen/country-flags#89]
Firefox 112.0b9 / Windows 11 22H2

Left click action: open IP or Host services
IP utility: https://iplookup.flagfox.net/?ip=[ip]&host=[host]
Host utility: https://iplookup.flagfox.net/?ip=[ip]&host=[host]
Optional permissions are on.

when I click flag, "obj is undefined" message is displayed.

**Comment by dallas7** [comment]
flagfox has been largely disfunctional for almost two years now.

**Comment by circcc** [comment]
[iplookup.flagfox.net](https://iplookup.flagfox.net/?ip=%5Bip%5D&host=%5Bhost%5D) site is working.
and when I add it to right click menu(https://iplookup.flagfox.net/?host=[host]) it is working. but, left click action is not working.

**Comment by aeri** [comment]
I am getting the same problem with the default installation without changing any parameters since the last version of the addon.

**Comment by andy-portmen** [comment]
Please reopen if you still have the issue with the `0.6.0.1` release.
