### ISSUE TITLE
left click action problems

### ISSUE THREAD

**Issue by HamidZaeri** [andy-portmen/country-flags#9]
Open in the background does not work for left click.
And left click always run the IP utility and never host utility.

**Comment by andy-portmen** [comment]
> Open in the background does not work for left click.

Okay, I can fix this.

> And left click always run the IP utility and never host utility.

This is the expected behavior. Host utility is only used when IP is not resolvable (just a complementary tool instead of displaying an error)

**Comment by HamidZaeri** [comment]
> This is the expected behavior. Host utility is only used when IP is not resolvable (just a complementary tool instead of displaying an error)
I tried switching their service URL to make left click show host info but it didn't work! In the URL it shows [host] itself!

And no more than 6 options show in the context menu.

**Comment by andy-portmen** [comment]
> I tried switching their service URL to make left click show host info but it didn't work! In the URL it shows [host] itself!

This is already fixed on the dev version, so that it has better support for custom URLs.

> And no more than 6 options show in the context menu.

WebExtension limitation. No workaround for this.

**Comment by HamidZaeri** [comment]
> WebExtension limitation. No workaround for this.

So, A feature to completely edit current right-click options (URL + title and text) or add custom commands up to 6 options.

**Comment by andy-portmen** [comment]
Currently on the dev version, we have two custom items and 8 defaults that user can select 6 items from. You can give it a try right now https://github.com/andy-portmen/country-flags/archive/master.zip
