### ISSUE TITLE
Way too many "red X on white" flags Part 2

### ISSUE THREAD

**Issue by dallas7** [andy-portmen/country-flags#90]
Using 0.6.0.1
That "red X on white flag" flag remains on your webextension dot org site.

Sample sites:
UPI dot com
garmin dot com
mailstore dot com
sammyfans dot com

Advise if you need more info about my setup.  If the issue is on my end, I can live with it.  Cheers.

_Originally posted by @dallas7 in https://github.com/andy-portmen/country-flags/issues/88#issuecomment-1501203968_

**Comment by andy-portmen** [comment]
How about the `0.6.1` release?

**Comment by dallas7** [comment]
0.6.1 works A-OK.  Thanks!!
