### ISSUE TITLE
Server hostname

### ISSUE THREAD

**Issue by Paskal-MY** [andy-portmen/country-flags#95]
Hi, is it possible to add server hostname next to the IP number?

Example as below, which is working in Firefox version 56, but not later version. The extension used is called WorldIP.

![svrhstnm](https://github.com/andy-portmen/country-flags/assets/64848367/d99c45a5-a3e4-4998-9065-f4fdd0d10224)

**Comment by andy-portmen** [comment]
This extension allows you to execute custom commands at the operating system level and view the output in the tooltip area of the action button.


Read FAQ 13
https://webextension.org/listing/country-flags.html?sg
